import * as _Bool   from './Bool';
import * as _Char   from './Char';
import * as _Either from './Either';
import * as _Eq     from './Eq';
import * as _Ix     from './Ix';
import * as _List   from './List';
import * as _Map    from './Map';
import * as _Maybe  from './Maybe';
import * as _Ord    from './Ord';
import * as _String from './String';
import * as _Tuple  from './Tuple';

export const Bool   = _Bool;
export const Char   = _Char;
export const Either = _Either;
export const Eq     = _Eq;
export const Ix     = _Ix;
export const List   = _List;
export const Map    = _Map;
export const Maybe  = _Maybe;
export const Ord    = _Ord;
export const String = _String;
export const Tuple  = _Tuple;
